name: Algorithmic Battle

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
    - name: Lint with flake8
      run: |
        flake8 . --count --max-complexity=10  --max-line-length=127  \
        --per-file-ignores="__init__.py:F401,D104 */solver_execution_error/main.py:E999 \
        */generator_execution_error/main.py:E999 match.py:E221 setup.py:D102,D100 \
        */verifier.py:D102 */parser.py:D102 tests/*:D102 tests/__init__.py:D104 \
        scripts/battle:E501,C901" \
        --docstring-convention numpy --show-source --statistics --ignore=D105,D401,W503

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Test using unittests
      run: |
        git clone https://github.com/Benezivas/algobattle.git
        cd algobattle && pip install . --user && cd ..
        python -m unittest

  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        git clone https://github.com/Benezivas/algobattle.git
        cd algobattle && pip install . --user && cd ..
    - name: Run short battles with different options as a sanity check
      run: |
        $HOME/.local/bin/battle problems/biclique --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
        $HOME/.local/bin/battle problems/c4subgraphiso --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
        $HOME/.local/bin/battle problems/clusterediting --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
        $HOME/.local/bin/battle problems/domset --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
        $HOME/.local/bin/battle problems/hikers --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
        $HOME/.local/bin/battle problems/oscm3 --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
        $HOME/.local/bin/battle problems/pairsum --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
        $HOME/.local/bin/battle problems/pathpacking --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
        $HOME/.local/bin/battle problems/scheduling --verbose --iter_cap=10 --rounds=2 --no_overhead_calculation
